version: '4.28'

services:
  nestjs_api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:${API_PORT}'
    volumes:
      - ./src:/app/src
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:16.3
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${PG_PORT}'
    volumes:
      - pgdata:/data/pgdata
volumes:
  pgdata: {}
